<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Http\Resources\VocationalProfileResource;
use App\Jobs\EmailResultsJob;
use App\Models\Assessment;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class ResultsController extends Controller
{
    public function show(Request $request, Assessment $assessment): VocationalProfileResource|JsonResponse
    {
        $this->authorizeAccess($request, $assessment);

        $profile = $assessment->vocationalProfile;

        if (! $profile) {
            $statusCode = match ($assessment->status) {
                'analyzing' => 202,
                'failed' => 500,
                default => 404,
            };

            return response()->json([
                'status' => $assessment->status,
                'message' => match ($assessment->status) {
                    'analyzing' => 'Your vocational profile is being prepared. This typically takes 1-2 minutes.',
                    'failed' => 'We encountered an issue analyzing your assessment. Please try again.',
                    default => 'No results available yet.',
                },
            ], $statusCode);
        }

        $resource = new VocationalProfileResource($profile);

        // Free tier: limit visible sections
        $user = $assessment->user;
        if (! $user || ! $user->subscribed()) {
            $resource->additional([
                'tier' => 'free',
                'locked_sections' => ['primary_pathways', 'specific_considerations', 'next_steps'],
                'upgrade_message' => 'Unlock your complete vocational profile — including specific career pathways, personalized considerations, and actionable next steps.',
            ]);
        }

        $resource->additional([
            'disclaimer' => 'This vocational profile was generated by AI and is intended as a tool for reflection and discernment, not as professional career counseling.',
        ]);

        return $resource;
    }

    public function email(Request $request, Assessment $assessment): JsonResponse
    {
        $this->authorizeAccess($request, $assessment);

        $validated = $request->validate([
            'email' => 'required|email',
        ]);

        $profile = $assessment->vocationalProfile;
        if (! $profile) {
            return response()->json(['error' => 'Results are not ready yet.'], 422);
        }

        EmailResultsJob::dispatch($assessment, $validated['email']);

        return response()->json(['message' => 'Results will be emailed shortly.']);
    }

    private function authorizeAccess(Request $request, Assessment $assessment): void
    {
        $user = $request->user();

        if ($user && $assessment->user_id === $user->id) {
            return;
        }

        if (! $user && $request->header('X-Guest-Token') === $assessment->guest_token) {
            return;
        }

        abort(403, 'Unauthorized access to assessment.');
    }
}
