<?php

use App\Enums\CollegeControl;
use App\Enums\CollegeKind;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Colleges, as published facts rather than as opinions.
     *
     * Every numeric column here is something the institution or the federal
     * IPEDS tables already report. Nothing in this table is a score, a rating
     * or a rank, and there is deliberately nowhere to put one — a `rating`
     * column would be filled within a month, and the moment a college carries
     * a number the explorer becomes a league table rather than a way to find
     * the place that fits this student.
     *
     * `gpa_25th` / `gpa_75th` are the middle-half range of admitted students,
     * which is the only admissions figure published widely enough to compute
     * anything honest from. They are nullable because plenty of institutions
     * — every open-admission community college, for a start — do not publish
     * one, and a missing range must read as "not enough to say" rather than
     * silently becoming a zero that makes everyone look admissible.
     *
     * `net_price_by_income` is the average price actually paid after aid, per
     * federal income bracket. It exists because the sticker price is the
     * single most misleading number in American education: it is what stops
     * students applying, and it is almost never what they would pay.
     */
    public function up(): void
    {
        Schema::create('colleges', function (Blueprint $table) {
            $table->uuid('id')->primary();

            $table->string('name');
            $table->string('slug')->unique();
            $table->string('city');
            $table->string('state', 2);

            $table->enum('control', CollegeControl::values());
            $table->enum('kind', CollegeKind::values());

            /*
             | Published admissions facts. `acceptance_rate` is stored as a
             | fraction and is a fact about the institution, not a score about
             | the student — it is never combined with anything of the
             | student's to produce a "match".
             */
            $table->decimal('acceptance_rate', 4, 3)->nullable();
            $table->decimal('gpa_25th', 3, 2)->nullable();
            $table->decimal('gpa_75th', 3, 2)->nullable();
            $table->boolean('test_optional')->default(true);

            /*
             | Cost. Sticker first, then what people actually pay.
             */
            $table->unsignedInteger('tuition_in_state');
            $table->unsignedInteger('tuition_out_of_state');
            $table->unsignedInteger('room_and_board')->default(0);
            $table->json('net_price_by_income')->nullable();

            /*
             | The application itself. The URL is stored so the walkthrough can
             | hand over a real link — the product guides and never applies.
             */
            $table->string('application_system')->nullable();
            $table->string('application_url');
            $table->unsignedTinyInteger('deadline_month')->nullable();
            $table->unsignedTinyInteger('deadline_day')->nullable();
            $table->unsignedInteger('application_fee')->default(0);
            $table->boolean('fee_waiver_available')->default(true);

            $table->timestamps();

            $table->index(['state', 'kind']);
        });

        /*
         | How a college reaches a student's portrait. The pivot is what makes
         | "filtering in real time based on everything the student is saying"
         | a join rather than a model call — the vocational categories are
         | already derived from verified signals, so a college surfaces
         | because of what the student said, and the path from the saying to
         | the surfacing is a foreign key somebody can read.
         */
        Schema::create('college_vocational_category', function (Blueprint $table) {
            /*
             | No surrogate key. A pure pivot's identity is the pair it joins,
             | and a uuid primary key here would have to be generated by hand
             | at every `attach()` — which is a thing somebody forgets.
             */
            $table->foreignUuid('college_id')->constrained()->cascadeOnDelete();
            $table->foreignUuid('vocational_category_id')->constrained()->cascadeOnDelete();

            /*
             | What the college actually calls the programme. Shown instead of
             | our taxonomy label wherever possible: a student searching for
             | "Respiratory Therapy" should see the words on the college's own
             | page, not our internal category name.
             */
            $table->string('program_name');
            $table->string('program_url')->nullable();
            $table->timestamps();

            $table->unique(['college_id', 'vocational_category_id', 'program_name'], 'college_program_unique');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('college_vocational_category');
        Schema::dropIfExists('colleges');
    }
};
