<?php

namespace App\Ai\Agents;

use Laravel\Ai\Attributes\Model;
use Laravel\Ai\Attributes\Provider;
use Laravel\Ai\Attributes\Timeout;
use Laravel\Ai\Contracts\Agent;
use Laravel\Ai\Promptable;
use Stringable;

#[Provider('anthropic')]
#[Model('claude-sonnet-4-20250514')]
#[Timeout(60)]
class CoverLetterWriterAgent implements Agent
{
    use Promptable;

    public function __construct(
        protected array $careerProfile,
        protected array $vocationalProfile,
        protected array $jobDescription,
        protected ?array $companyResearch,
        protected ?array $voiceProfile = null,
    ) {}

    public function instructions(): Stringable|string
    {
        $bannedPhrases = implode(', ', array_merge(
            ['leverage', 'synergy', 'I\'m excited to apply', 'passionate about', 'proven track record', 'results-driven', 'in today\'s fast-paced world', 'I am writing to express my interest'],
            $this->voiceProfile['banned_phrases'] ?? []
        ));

        return <<<INSTRUCTIONS
You are a cover letter writer who creates authentic, personalized cover letters using the 3-touch personalization method. Each letter must feel like it was written by the applicant, not generated by AI.

## 3-Touch Personalization Method

Every cover letter must include these three distinct personalization layers:

1. **Company Research Touch**: Reference something specific about the company — their mission, a recent initiative, a product, or a value that resonates with the applicant. This shows the applicant researched the company. If company research data is provided, use it. If not, use what's in the job description.

2. **Role Alignment Touch**: Connect 2-3 specific experiences from the applicant's history to specific requirements in the job description. Don't restate the job requirements — show how the applicant's experience maps to them.

3. **Personal Story Touch**: Connect the applicant's vocational calling to this role. Use their vocational profile to explain WHY this work matters to them personally. This is where the theology of vocation becomes powerful — "My calling to [primary pathway] draws me to this work because..."

## Anti-AI-Slop Rules
- NEVER use these phrases: {$bannedPhrases}
- NEVER start with "Dear Hiring Manager, I am writing to express my interest in..."
- Start with something specific — a connection to the company, a relevant experience, or a direct statement about why this role matters
- Write at a conversational-professional register, not academic
- Keep to 3-4 paragraphs, under 400 words
- End with a specific call to action, not a generic "I look forward to hearing from you"

## Voice Matching
If a voice profile is provided, match the applicant's natural writing style — their sentence length, vocabulary level, and tone register.

## Output
Return the complete cover letter as plain text. No headers, no addresses — just the letter body.
INSTRUCTIONS;
    }

    public function buildPrompt(): string
    {
        $career = json_encode($this->careerProfile, JSON_PRETTY_PRINT);
        $vocation = json_encode($this->vocationalProfile, JSON_PRETTY_PRINT);
        $job = json_encode($this->jobDescription, JSON_PRETTY_PRINT);

        $companySection = '';
        if ($this->companyResearch) {
            $company = json_encode($this->companyResearch, JSON_PRETTY_PRINT);
            $companySection = "\n## Company Research\n{$company}";
        }

        $voiceSection = '';
        if ($this->voiceProfile) {
            $voice = json_encode($this->voiceProfile, JSON_PRETTY_PRINT);
            $voiceSection = "\n## Voice Profile (match this person's writing style)\n{$voice}";
        }

        return <<<PROMPT
Write a cover letter for the following person, tailored to the specific job.

## Career History
{$career}

## Vocational Profile (their calling and strengths)
{$vocation}

## Target Job
{$job}
{$companySection}
{$voiceSection}
PROMPT;
    }
}
