<?php

namespace App\Http\Controllers\Web;

use App\Enums\FeedbackQuestion;
use App\Enums\FeedbackStanding;
use App\Http\Controllers\Controller;
use App\Models\Assessment;
use App\Models\EvaluationFeedback;
use App\Support\AssessmentAccess;
use App\Support\EngineVersion;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

/**
 * Roadmap 0.5 — capturing what the student thought.
 *
 * Open to guests as well as account holders, because the assessment itself is:
 * requiring a login before someone can tell us the portrait is wrong would
 * filter the sample down to the people it worked for, which is exactly the
 * population whose opinion we least need.
 */
class EvaluationFeedbackController extends Controller
{
    public function store(Request $request, Assessment $assessment): RedirectResponse
    {
        AssessmentAccess::authorize($request, $assessment);

        $validated = $request->validate([
            'question' => ['required', Rule::in(FeedbackQuestion::values())],
            'standing' => ['required', Rule::in(FeedbackStanding::values())],
            'comment' => ['nullable', 'string', 'max:2000'],
            'guest_token' => ['nullable', 'string'],
        ]);

        /**
         * The prompt version is stamped here rather than read from the profile
         * so that feedback on a result stays attributable even if the profile
         * is later regenerated by a newer engine. Otherwise every historical
         * complaint silently migrates onto whichever prompt is current, and
         * the prompt that caused it looks clean.
         */
        EvaluationFeedback::firstOrCreate(
            [
                'assessment_id' => $assessment->id,
                'question' => $validated['question'],
            ],
            [
                'user_id' => $assessment->user_id,
                'standing' => $validated['standing'],
                'comment' => $validated['comment'] ?? null,
                'prompt_version' => $assessment->vocationalProfile?->prompt_version ?? EngineVersion::prompt(),
            ],
        );

        return back();
    }

    /**
     * A student may only rate their own result.
     *
     * Guests present the token their assessment already issued them, which is
     * the same proof `Api\V1\AssessmentController` accepts — so this opens no
     * new door, and it closes the one where any signed-in user could post
     * feedback onto a stranger's assessment by guessing a UUID.
     *
     * Note this endpoint is stricter than the results page it sits beside,
     * which currently authorizes nobody at all. That is a real defect and it
     * is recorded in the roadmap; it is not fixed here because guests reach
     * results by link and the correct fix is a product decision about how long
     * such a link should stay live, not a line of middleware.
     */
}
