<?php

namespace App\Support;

class VocationalProfileCopy
{
    public static function forLocale(?string $locale): array
    {
        return match (ConversationLocale::normalize($locale)) {
            'es-419' => self::spanish(),
            'pt-BR' => self::portuguese(),
            default => self::english(),
        };
    }

    protected static function english(): array
    {
        return [
            'email_subject' => 'Your Vocational Profile',
            'title' => 'Your Vocational Profile',
            'subtitle' => 'A synthesis of your gifts, inclinations, and next vocational steps',
            'opening_synthesis' => 'Opening Synthesis',
            'vocational_orientation' => 'Vocational Orientation',
            'primary_domain' => 'Primary Domain',
            'mode_of_work' => 'Mode of Work',
            'secondary_orientation' => 'Secondary Orientation',
            'primary_pathways' => 'Primary Pathways',
            'specific_considerations' => 'Specific Considerations',
            'next_steps' => 'Next Steps',
            'ministry_integration' => 'Ministry Integration',
            'not_specified' => 'Not specified',
            'return_to_results' => 'Return to Your Results',
            'return_to_results_anytime' => 'Return to your results anytime',
            'disclaimer' => 'This vocational profile was generated by AI and is intended as a tool for reflection and discernment, not as professional career counseling.',
            'status_analyzing' => 'Your vocational profile is being prepared. This typically takes 1-2 minutes.',
            'status_failed' => 'We encountered an issue analyzing your assessment. Please try again.',
            'status_missing' => 'No results available yet.',
            'results_not_ready' => 'Results are not ready yet.',
            'results_emailed' => 'Results will be emailed shortly.',
        ];
    }

    protected static function spanish(): array
    {
        return [
            'email_subject' => 'Tu perfil vocacional',
            'title' => 'Tu perfil vocacional',
            'subtitle' => 'Una síntesis de tus dones, inclinaciones y próximos pasos vocacionales',
            'opening_synthesis' => 'Síntesis inicial',
            'vocational_orientation' => 'Orientación vocacional',
            'primary_domain' => 'Dominio principal',
            'mode_of_work' => 'Modo de trabajo',
            'secondary_orientation' => 'Orientación secundaria',
            'primary_pathways' => 'Caminos principales',
            'specific_considerations' => 'Consideraciones específicas',
            'next_steps' => 'Próximos pasos',
            'ministry_integration' => 'Integración con el ministerio',
            'not_specified' => 'No especificado',
            'return_to_results' => 'Volver a tus resultados',
            'return_to_results_anytime' => 'Vuelve a tus resultados en cualquier momento',
            'disclaimer' => 'Este perfil vocacional fue generado con ayuda de IA y está pensado como una herramienta de reflexión y discernimiento, no como orientación profesional de carrera.',
            'status_analyzing' => 'Tu perfil vocacional se está preparando. Esto normalmente tarda entre 1 y 2 minutos.',
            'status_failed' => 'Encontramos un problema al analizar tu evaluación. Inténtalo de nuevo.',
            'status_missing' => 'Aún no hay resultados disponibles.',
            'results_not_ready' => 'Los resultados todavía no están listos.',
            'results_emailed' => 'Los resultados se enviarán por correo en breve.',
        ];
    }

    protected static function portuguese(): array
    {
        return [
            'email_subject' => 'Seu perfil vocacional',
            'title' => 'Seu perfil vocacional',
            'subtitle' => 'Uma síntese dos seus dons, inclinações e próximos passos vocacionais',
            'opening_synthesis' => 'Síntese inicial',
            'vocational_orientation' => 'Orientação vocacional',
            'primary_domain' => 'Domínio principal',
            'mode_of_work' => 'Modo de trabalho',
            'secondary_orientation' => 'Orientação secundária',
            'primary_pathways' => 'Caminhos principais',
            'specific_considerations' => 'Considerações específicas',
            'next_steps' => 'Próximos passos',
            'ministry_integration' => 'Integração ministerial',
            'not_specified' => 'Não especificado',
            'return_to_results' => 'Voltar aos seus resultados',
            'return_to_results_anytime' => 'Volte aos seus resultados a qualquer momento',
            'disclaimer' => 'Este perfil vocacional foi gerado com ajuda de IA e foi pensado como uma ferramenta de reflexão e discernimento, não como orientação profissional de carreira.',
            'status_analyzing' => 'Seu perfil vocacional está sendo preparado. Isso normalmente leva de 1 a 2 minutos.',
            'status_failed' => 'Encontramos um problema ao analisar sua avaliação. Tente novamente.',
            'status_missing' => 'Ainda não há resultados disponíveis.',
            'results_not_ready' => 'Os resultados ainda não estão prontos.',
            'results_emailed' => 'Os resultados serão enviados por e-mail em breve.',
        ];
    }
}
